on:
  schedule:
    - cron: "*/60 * * * *"

name: Crowdin Sync

jobs:
  crowdin-sync:
    runs-on: ubuntu-latest

    - name: Checkout
      uses: actions/checkout@v2

    steps:
      - name: crowdin-action
        uses: crowdin/github-action@1.4.11
        with:
          upload_translations: true
          download_translations: true
          export_only_approved: true
          push_translations: true
          commit_message: 'Update the localization files'
          localization_branch_name: translations
          create_pull_request: true
          pull_request_title: 'Update the localization files'
          pull_request_body: 'These are the newest translations from [Crowdin](https://crowdin.com/project/project-lighthouse)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
